title: Borja Freire Castro
email: borja.freire1@udc.es//borjaf696@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal page. 
baseurl: ""
url: "https://github.com/borjaf696/"

socials:
  - title: Email
    icon: fas fa-envelope
    url: mailto:borjaf696@udc.es
  - title: Github
    icon: fab fa-github
    url: https://github.com/borjaf696/
  - title: ORCID
    icon: fab fa-orcid
    url: https://orcid.org/0000-0003-0317-5482
  - title: ResearchGate
    icon: ai ai-researchgate
    url: https://www.researchgate.net/profile/Borja-Freire-Castro/

# Build settings
plugins:
  - jekyll-analytics
  - jekyll-sitemap

collections:
  publications:
    output: true
  software:
    output: false

jekyll_analytics:
  GoogleAnalytics:
    id: UA-129572314-1
    anonymizeIp: false

# Exclude from processing.
# The following items will not be processed, by default:
#  .sass-cache/
#  .jekyll-cache/
#  gemfiles/
#  Gemfile
#  Gemfile.lock
#  node_modules/
#  vendor/bundle/
#  vendor/cache/
#  vendor/gems/
#  vendor/ruby/
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - scripts/
